### ISSUE TITLE
Unable to compile 

### ISSUE THREAD

**Issue by Dongshengc** [dclaxton/maximum-clique#1]
Can you give some instructions on how to compile and run this program?

**Comment by dclaxton** [comment]
Hi, sorry for the late reply, I do not check this repo often. 
here's how I compile it using g++ on Linux,
`g++ -o max_click maximumclique.cpp matrix.cpp edge.hpp Vertex.hpp`
you can then run it by executing `./max_click`
you can then enter your input (there's no prompt)
